# Generated by Django 3.1.2 on 2021-04-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210111_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='index',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='index',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
