# Generated by Django 3.1.2 on 2021-04-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210406_1132'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='session_index_b66a3a_idx',
        ),
    ]
