# Generated by Django 3.1.2 on 2021-04-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210407_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lap',
            name='dag',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='enhanced_avg_speed',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='event',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='jaar',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='lap_trigger',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='maand',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='message',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='message_index',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='total_timer_time',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='uur',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='week',
        ),
        migrations.RemoveField(
            model_name='record',
            name='enhanced_speed',
        ),
        migrations.RemoveField(
            model_name='record',
            name='message',
        ),
        migrations.RemoveField(
            model_name='record',
            name='name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='unknown',
        ),
        migrations.RemoveField(
            model_name='session',
            name='enhanced_avg_speed',
        ),
    ]
