# Generated by Django 3.1.2 on 2021-04-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210407_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lap',
            old_name='timestamp',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='timestamp',
            new_name='end_time',
        ),
    ]
