# Generated by Django 3.1.2 on 2021-04-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210407_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='quarter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
