# Generated by Django 3.1.2 on 2021-06-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210421_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='index',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
